---
name: Deploy Website with Surge

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Learning to Deploy using Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Setup Surge
        run: npm install --global surge
      - name: Execute Deployment with Surge
        run: surge ./ BootCamp-No-1.surge.sh --token ${{ secrets.Surge_Token }}

...
